### PR TITLE
swift

### PR DESCRIPTION
**Pull request by softdevstory**
swift version

### CODE REVIEW

**Review by originerd — CHANGES_REQUESTED** [review]
It's awesome….But It does not match with format.

https://github.com/originerd/awesome-lotto#format

**Comment by softdevstory** [comment]
I modified.

http://ideone.com/V2ddHq

**Comment by softdevstory** [comment]
It works well. http://ideone.com/V2ddHq

**Comment by softdevstory** [comment]
Duplicated.

**Pull request closed without merging**
